 const category_company  = [
        "Tecnología",
        "Salud",
        "Finanzas",
        "Educación",
        "Transporte",
        "Energía",
        "Bienes Raíces",
        "Retail",
        "Manufactura",
        "Telecomunicaciones",
        "Agricultura",
        "Alimentos y Bebidas",
        "Automotriz",
        "Medios y Entretenimiento",
        "Consultoría",
        "Turismo",
        "Construcción",
        "Seguros",
        "Logística",
        "Farmacéutica",
        "Moda y Textil",
        "Aeronáutica",
        "Minería",
        "Química",
        "Deportes",
        "Software",
        "Servicios Públicos",
        "Legal",
        "Marketing y Publicidad",
        "Arte y Cultura",
        "Inmobiliaria",
        "Recursos Humanos",
        "Servicios",
        "Otra",
    ];
    
     const typeCompanyEnum = [
        "Corporación",
        "Sociedad Anónima",
        "Sociedad de Responsabilidad Limitada (SRL)",
        "Startup",
        "Non-profit (Sin Fines de Lucro)",
        "Pública",
        "Privada",
        "Cooperativa",
        "Franquicia",
        "Empresa Unipersonal",
        "Joint Venture",
        "Otra",
      ];

module.exports = {
    category_company,
    typeCompanyEnum
}